FROM circleci/python:latest

# Install checkout requirements
RUN curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | bash && \
    apt-get install -y git-lfs && \
    git lfs install

# Checkout binaries
RUN git lfs pull

# Install build requirements
RUN apt-get install -y pngquant && \
    apt-get install -y python-enchant && \
    pip install -r requirements.txt