version: 2
jobs:
  build:
    working_directory: ~/work
    docker:
      - image: circleci/python:latest
    steps:
      - checkout
      - run:
          name: Install checkout requirements
          command: |
            curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
            sudo apt-get install git-lfs
            git lfs install
      - run:
          name: Checkout binaries
          command: git lfs pull
      - run:
          name: Install build requirements
          command: |
            sudo apt-get install pngquant
            sudo apt-get install python-enchant
            sudo pip install -r requirements.txt
      - run:
          name: Style Guide Testing
          command: |
            paths=$(git diff origin/master... --name-only)
            sudo python style-test.py $paths
      - run:
          name: Spell Checker
          command: |
            sphinx-build -b spelling src build/spelling
            python util/check-spelling-output.py
      - run:
          name: Build PDF
          command: |
            sphinx-build -b latex src build/latex
            sudo python util/resize.py
      - run:
          name: Build docs
          command: sphinx-build -W -b dirhtml src build
      - run:
          name: Compress images
          command: pngquant build/_images/*.png --force --ext .png --verbose
      - store_artifacts:
          path: build
          destination: build
      - persist_to_workspace:
          root: ~/work
          paths:
            - build/*
            - s3_website.yml
  build_pdf:
    working_directory: ~/work
    docker:
      - image: schickling/latex
    steps:
      - attach_workspace:
          at: ~/work
      - run:
          name: Build PDF
          command: |
              cd build/latex
              xelatex OpenDataKit.tex
              xelatex OpenDataKit.tex
              mv OpenDataKit.pdf ../_downloads/ODK-Documentation.pdf
      - store_artifacts:
          path: build/_downloads/ODK-Documentation.pdf
          destination: ODK-Documentation.pdf
      - persist_to_workspace:
          root: ~/work
          paths:
            - build/*
  deploy:
    working_directory: ~/work
    docker:
      - image: circleci/ruby:latest
    steps:
      - attach_workspace:
          at: ~/work
      - run:
          name: Install deploy requirements
          command: |
              if [[ "$CIRCLE_PROJECT_USERNAME" == "opendatakit" ]]; then \
                sudo apt-get install -y openjdk-8-jre-headless
                gem install s3_website && s3_website install
              fi
      - run:
          name: Push to S3
          command: |
              if [[ "$CIRCLE_PROJECT_USERNAME" == "opendatakit" ]]; then \
                s3_website push
              fi
workflows:
  version: 2
  build_deploy:
    jobs:
      - build
      - build_pdf:
          requires:
            - build
      - deploy:
          requires:
            - build
            - build_pdf
          # We'd like to also filter by username and remove the if/fi above, but username filtering is not supported in CircleCI
          filters:
            branches:
              only: master
