version: 2
jobs:
  build:
    working_directory: ~/work
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run:
          name: Install checkout requirements
          command: |
            sudo apt-get update
            sudo apt-get install git-lfs
      - run:
          name: Checkout binaries
          command: git lfs pull
      - run:
          name: Install build requirements
          command: |
            sudo apt-get install pngquant
            sudo apt-get install python3-enchant
            pip3 install --user -r requirements.txt 
      - run:
          name: Build html
          command: make dirhtml
      - run:
          name: Spell check
          command: |
            make spelling
            python3 util/check-spelling-output.py docs/_build/spelling
      - run:
          name: Compress images
          command: pngquant docs/_build/dirhtml/_images/*.png --force --ext .png --verbose
      - store_artifacts:
          path: docs/_build/dirhtml/
      - persist_to_workspace:
          root: ~/work
          paths:
            - docs/_build/dirhtml/*
            - s3_website.yml
  deploy:
    working_directory: ~/work
    docker:
      - image: cimg/ruby:3.2
    steps:
      - attach_workspace:
          at: ~/work
      - run:
          name: Install deploy requirements
          command: |
              if [[ "$CIRCLE_PROJECT_USERNAME" == "getodk" ]]; then \
                sudo apt-get update
                sudo apt-get install -y pngquant openjdk-11-jre-headless
                gem install s3_website_revived && s3_website install
              fi
      - run:
          name: Push to S3
          command: |
              if [[ "$CIRCLE_PROJECT_USERNAME" == "getodk" ]]; then \
                s3_website push
              fi

workflows:
  version: 2
  build_deploy:
    jobs:
      - build
      - deploy:
          context: AWS
          requires:
            - build
          filters:
            branches:
              only: master
