name: Build and Deploy

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: cimg/python:3.14

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          lfs: true

      - name: Install checkout requirements
        run: |
          sudo apt-get update
          sudo apt-get install -y git-lfs

      - name: Checkout binaries
        run: git lfs pull

      - name: Check that Git LFS was used to commit binaries
        run: |
          git ls-files | git check-attr --stdin filter | \
            awk -F': ' '$3 ~ /lfs/ { print $1}' | \
            xargs -L1 sh -c 'git cat-file blob "HEAD:$0" | \
            git lfs pointer --check --stdin || { echo "$0"; false; }'

      - name: Install build requirements
        run: |
          sudo apt-get update
          sudo apt-get install -y pngquant python3-enchant
          pip3 install --user -r requirements.txt --upgrade
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Build html
        run: make dirhtml

      - name: Spell check
        run: |
          make spelling
          python3 utils/check-spelling-output.py docs/_build/spelling

      - name: Compress images
        run: pngquant docs/_build/dirhtml/_images/*.png --force --ext .png --verbose

      - name: Store artifacts
        uses: actions/upload-artifact@v7
        with:
          name: dirhtml-artifacts
          path: docs/_build/dirhtml/

      - name: Persist build output to workspace
        uses: actions/upload-artifact@v7
        with:
          name: deploy-workspace
          path: |
            docs/_build/dirhtml
            s3_website.yml

  deploy:
    needs: build
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    runs-on: ubuntu-latest
    container:
      image: cimg/ruby:3.2
    environment: AWS
    env:
      PROJECT_USERNAME: ${{ github.repository_owner }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Download workspace files
        uses: actions/download-artifact@v7
        with:
          name: deploy-workspace
          path: .

      - name: Install deploy requirements
        run: |
          if [[ "$PROJECT_USERNAME" == "getodk" ]]; then
            sudo apt-get update
            sudo apt-get install -y pngquant openjdk-11-jre-headless
            gem install s3_website_revived && s3_website install
          fi

      - name: Push to S3
        run: |
          if [[ "$PROJECT_USERNAME" == "getodk" ]]; then
            s3_website push
          fi
